server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: a.elghazoui2000@gmail.com
    password: mnzd wsmr hcxh gdbu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: AutoDriveAIPlatformSecretKey2024VerySecureAndLongEnoughForHS512Algorithm
  expiration: 86400000
