server:
  port: 8085

spring:
  application:
    name: detection-service
  datasource:
    url: jdbc:mysql://localhost:3306/detection_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# Python Detection API configuration
detection:
  api:
    url: http://localhost:5000
    timeout: 300000
